In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('Basket_Fruits.csv')

In [4]:
df = data.copy()

In [5]:
transactions = df.set_index('TransactionID').stack().groupby(level=0).apply(list).tolist()

In [6]:
transactions

[['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],
 ['Carrot', 'Broccoli', 'Spinach'],
 ['Banana', 'Pineapple', 'Mango'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Orange', 'Lemon', 'Strawberry'],
 ['Tomato', 'Potato', 'Cucumber'],
 ['Apple', 'Grapes', 'Watermelon'],

In [7]:
ohe_df = pd.get_dummies(pd.DataFrame(transactions).stack()).groupby(level=0).sum()

In [8]:
ohe_df

,Apple,Banana,Broccoli,Carrot,Cucumber,Grapes,Lemon,Mango,Orange,Pineapple,Potato,Spinach,Strawberry,Tomato,Watermelon
0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0
2,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0
3,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0
4,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0
996,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
997,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1
998,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0
999,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0

In [11]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [12]:
frequent_itemsets = apriori(ohe_df,min_support=0.2,use_colnames=True)

In [13]:
frequent_itemsets

    support                     itemsets
0       0.2                      (Apple)
1       0.2                     (Banana)
2       0.2                   (Broccoli)
3       0.2                     (Carrot)
4       0.2                   (Cucumber)
5       0.2                     (Grapes)
6       0.2                      (Lemon)
7       0.2                      (Mango)
8       0.2                     (Orange)
9       0.2                  (Pineapple)
10      0.2                     (Potato)
11      0.2                    (Spinach)
12      0.2                 (Strawberry)
13      0.2                     (Tomato)
14      0.2                 (Watermelon)
15      0.2              (Grapes, Apple)
16      0.2          (Watermelon, Apple)
17      0.2              (Mango, Banana)
18      0.2          (Pineapple, Banana)
19      0.2           (Broccoli, Carrot)
20      0.2          (Broccoli, Spinach)
21      0.2            (Spinach, Carrot)
22      0.2           (Potato, Cucumber)
23      0.2           (Tomato, Cucumber)
24      0.2         (Grapes, Watermelon)
25      0.2              (Orange, Lemon)
26      0.2          (Lemon, Strawberry)
27      0.2           (Mango, Pineapple)
28      0.2         (Orange, Strawberry)
29      0.2             (Tomato, Potato)
30      0.2  (Grapes, Watermelon, Apple)
31      0.2   (Mango, Pineapple, Banana)
32      0.2  (Spinach, Broccoli, Carrot)
33      0.2   (Tomato, Potato, Cucumber)
34      0.2  (Lemon, Orange, Strawberry)

In [14]:
rules = association_rules(frequent_itemsets,metric='confidence',min_threshold=0.5)

In [15]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Grapes),(Apple),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
1,(Apple),(Grapes),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
2,(Watermelon),(Apple),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
3,(Apple),(Watermelon),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
4,(Mango),(Banana),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
5,(Banana),(Mango),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
6,(Pineapple),(Banana),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
7,(Banana),(Pineapple),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
8,(Broccoli),(Carrot),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
9,(Carrot),(Broccoli),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
10,(Broccoli),(Spinach),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
11,(Spinach),(Broccoli),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
12,(Spinach),(Carrot),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
13,(Carrot),(Spinach),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
14,(Potato),(Cucumber),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
15,(Cucumber),(Potato),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
16,(Tomato),(Cucumber),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
17,(Cucumber),(Tomato),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
18,(Grapes),(Watermelon),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
19,(Watermelon),(Grapes),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
20,(Orange),(Lemon),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
21,(Lemon),(Orange),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
22,(Strawberry),(Lemon),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
23,(Lemon),(Strawberry),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
24,(Mango),(Pineapple),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
25,(Pineapple),(Mango),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
26,(Orange),(Strawberry),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
27,(Strawberry),(Orange),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
28,(Tomato),(Potato),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
29,(Potato),(Tomato),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
30,"(Grapes, Watermelon)",(Apple),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
31,"(Grapes, Apple)",(Watermelon),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
32,"(Watermelon, Apple)",(Grapes),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
33,(Grapes),"(Watermelon, Apple)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
34,(Watermelon),"(Grapes, Apple)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
35,(Apple),"(Grapes, Watermelon)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
36,"(Mango, Pineapple)",(Banana),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
37,"(Mango, Banana)",(Pineapple),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
38,"(Pineapple, Banana)",(Mango),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
39,(Mango),"(Pineapple, Banana)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
40,(Pineapple),"(Mango, Banana)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
41,(Banana),"(Mango, Pineapple)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
42,"(Spinach, Broccoli)",(Carrot),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
43,"(Spinach, Carrot)",(Broccoli),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
44,"(Broccoli, Carrot)",(Spinach),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
45,(Spinach),"(Broccoli, Carrot)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
46,(Broccoli),"(Spinach, Carrot)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
47,(Carrot),"(Spinach, Broccoli)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
48,"(Tomato, Potato)",(Cucumber),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
49,"(Tomato, Cucumber)",(Potato),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
50,"(Potato, Cucumber)",(Tomato),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
51,(Tomato),"(Potato, Cucumber)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
52,(Potato),"(Tomato, Cucumber)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
53,(Cucumber),"(Tomato, Potato)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
54,"(Orange, Strawberry)",(Lemon),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
55,"(Orange, Lemon)",(Strawberry),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
56,"(Lemon, Strawberry)",(Orange),0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
57,(Orange),"(Lemon, Strawberry)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
58,(Strawberry),"(Orange, Lemon)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0
59,(Lemon),"(Orange, Strawberry)",0.2,0.2,0.2,1.0,5.0,1.0,0.16,inf,1.0,1.0,1.0,1.0